import { LegalPageLayout, LegalSection } from '../_components/legal-page-layout'

export const metadata = {
  title: 'Privacy Policy — QBR Deck',
}

export default function PrivacyPolicyPage() {
  return (
    <LegalPageLayout title="Privacy Policy" effectiveDate="September 6, 2026">
      <LegalSection heading="1. Who operates QBR Deck">
        <p>
          QBR Deck is a SaaS product operated by MI Secure Tech Solutions ("QBR Deck,"
          "we," "us," or "our"). This Privacy Policy explains what information we collect
          through the QBR Deck application at qbrdeck.misecuretechsolutions.com, how we
          use it, and the choices available to you.
        </p>
      </LegalSection>

      <LegalSection heading="2. Information you provide to us">
        <p>We collect information that you or your organization provide directly, including:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Account and profile information (such as name and email address) collected when you sign up or sign in.</li>
          <li>Workspace and company information, such as your workspace/organization name.</li>
          <li>Client and QBR content you enter into the product — for example client names, contacts, metrics, tickets, wins, risks, and other business data used to generate Quarterly Business Review decks.</li>
          <li>Branding assets you choose to upload, such as a company logo, on plans that support custom branding.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="3. Information collected automatically">
        <p>
          To operate and secure the service, we and our infrastructure providers process
          standard technical information generated by your use of the application, such as
          request and error logs. We do not currently operate third-party advertising or
          website-analytics trackers, and we do not use cookies or local browser storage
          for advertising or cross-site tracking purposes. Authentication uses session
          cookies set by our sign-in provider (Clerk) solely to keep you signed in.
        </p>
      </LegalSection>

      <LegalSection heading="4. Payment information">
        <p>
          Subscription payments are processed by Stripe. QBR Deck does not receive or store
          your full card number — Stripe handles collection and storage of payment card
          details in accordance with its own privacy and security practices.
        </p>
      </LegalSection>

      <LegalSection heading="5. Service providers we use">
        <p>To provide QBR Deck, we rely on the following service providers to process data on our behalf:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li><strong>Stripe</strong> — payment processing and subscription billing.</li>
          <li><strong>Clerk</strong> — user authentication and account sign-in.</li>
          <li><strong>Supabase</strong> — hosted database storage for application data.</li>
          <li><strong>Vercel</strong> — application hosting.</li>
          <li><strong>Vercel Blob</strong> — storage for uploaded branding assets such as logos.</li>
          <li><strong>Anthropic</strong> — AI processing used to generate QBR content (see Section 7).</li>
          <li><strong>Resend</strong> — delivery of transactional emails (such as QBR-ready notices and billing emails).</li>
        </ul>
      </LegalSection>

      <LegalSection heading="6. How we use information">
        <p>We use the information described above to:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Provide, maintain, and secure your account and workspace;</li>
          <li>Generate QBR content and exports (PDF/PPTX) that you request;</li>
          <li>Process subscription billing and payments;</li>
          <li>Support exporting and sharing of QBRs that you initiate;</li>
          <li>Send account, billing, and product-related communications; and</li>
          <li>Operate, secure, and improve the service.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="7. AI processing">
        <p>
          When you use QBR Deck's AI-powered generation feature, the client and metrics
          information you submit for that QBR is sent to our AI service provider,
          Anthropic, as needed to generate the requested content. We do not make
          representations here about Anthropic's own data training or retention
          practices beyond what Anthropic separately publishes; please contact us if you
          have questions about how AI-submitted content is handled.
        </p>
      </LegalSection>

      <LegalSection heading="8. Sharing of information">
        <p>
          We do not sell your personal information. We share information only with the
          service providers described in Section 5 as needed to operate QBR Deck, or as
          required by law.
        </p>
      </LegalSection>

      <LegalSection heading="9. Data retention">
        <p>
          We retain account, workspace, and QBR data for as long as your account or
          workspace remains active, and for as long as reasonably necessary afterward for
          legitimate operational, security, or legal purposes. If a paid subscription
          ends, your existing client and QBR content is not automatically deleted merely
          because the workspace reverts to the Free plan.
        </p>
      </LegalSection>

      <LegalSection heading="10. Share links you create">
        <p>
          QBR Deck lets you generate share links so clients can view a QBR report online.
          You control what you share and with whom through these links — anyone with a
          valid link can view the associated report, so treat share links as you would any
          other sensitive document link.
        </p>
      </LegalSection>

      <LegalSection heading="11. Security">
        <p>
          We use reasonable technical and organizational measures designed to protect
          information processed through QBR Deck. No method of transmission or storage is
          completely secure, and we cannot guarantee absolute security.
        </p>
      </LegalSection>

      <LegalSection heading="12. Access, correction, and deletion">
        <p>
          You can update most account and workspace information directly within the
          product. For requests to access, correct, or delete information that you cannot
          manage yourself, contact us at{' '}
          <a href="mailto:support@misecuretechsolutions.com" className="text-navy-700 underline">
            support@misecuretechsolutions.com
          </a>{' '}
          and we will respond to your request.
        </p>
      </LegalSection>

      <LegalSection heading="13. Children's privacy">
        <p>
          QBR Deck is a business tool intended for use by MSP (managed service provider)
          professionals and their organizations. It is not directed to, and should not be
          used by, children.
        </p>
      </LegalSection>

      <LegalSection heading="14. International use">
        <p>
          QBR Deck and its service providers may process information in the United States
          and other locations where our providers operate. By using QBR Deck, you
          understand that information may be processed outside your own country.
        </p>
      </LegalSection>

      <LegalSection heading="15. Changes to this policy">
        <p>
          We may update this Privacy Policy from time to time. If we make material
          changes, we will update the effective date above.
        </p>
      </LegalSection>

      <LegalSection heading="16. Contact us">
        <p>
          Questions about this Privacy Policy can be sent to{' '}
          <a href="mailto:support@misecuretechsolutions.com" className="text-navy-700 underline">
            support@misecuretechsolutions.com
          </a>.
        </p>
      </LegalSection>
    </LegalPageLayout>
  )
}
