import { auth } from '@clerk/nextjs/server'
import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import { prisma } from '@/lib/prisma'
import { getWorkspaceMembership } from '@/lib/workspace'
import { can } from '@/lib/permissions'
import { resolveBranding, buildFooterText } from '@/lib/branding'
import { resolveHealthScore } from '@/lib/health-score'
import { resolveSlides, buildPlaceholderContext, sanitizeResolvedSlides } from '@/lib/placeholders'

// Minimal structural validation only — slides is persisted as Prisma Json?
// with no fixed shape, and historical QBRs may have been generated by an
// earlier generatorVersion. This intentionally does not mirror the full
// QBRSlide interface (lib/anthropic.ts) field-by-field, so it never rejects
// a legitimate save merely because a slide's internal shape has drifted
// over time — it only rejects the malformed-request class (missing/null/
// non-array slides, or an array containing non-object entries).
const patchSchema = z.object({
  slides: z.array(z.record(z.string(), z.unknown())),
})

export async function GET(req: NextRequest, { params }: { params: { qbrId: string } }) {
  try {
    const { userId: clerkId } = auth()
    if (!clerkId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const membership = await getWorkspaceMembership(clerkId)
    if (!membership) return NextResponse.json({ error: 'Workspace not found' }, { status: 404 })

    if (!can.viewQBR(membership.role))
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })

    const qbr = await prisma.qBR.findFirst({
      where: { id: params.qbrId, workspaceId: membership.workspaceId, deletedAt: null },
      include: { client: true },
    })

    if (!qbr) return NextResponse.json({ error: 'Not found' }, { status: 404 })

    // ── Workspace + branding — same pattern as export-pdf/export-pptx/portal ───
    const workspace = await prisma.workspace.findUnique({
      where: { id: membership.workspaceId },
    })

    const branding = resolveBranding({
      plan:          membership.subscription?.plan ?? 'FREE',
      workspaceName: workspace?.name ?? 'QBR Deck',
    })

    // ── Health score — same pattern as export-pdf/export-pptx/portal ───────────
    const healthResult = resolveHealthScore(qbr)

    // ── Footer — same pattern as export-pdf/export-pptx/portal ─────────────────
    const footerText = buildFooterText({
      branding,
      clientName: qbr.client.name,
      quarter:    qbr.quarter,
      year:       qbr.year,
    })

    // ── Resolve placeholders into a display-only copy ───────────────────────────
    // `qbr.slides` (below, via the spread) stays the raw, unresolved stored value —
    // unchanged in meaning and content. `resolvedSlides` is a new, additional field
    // for display only; nothing is written back to the database here.
    const placeholderCtx = buildPlaceholderContext({
      clientName:     qbr.client.name,
      clientIndustry: qbr.client.industry,
      quarter:        qbr.quarter,
      year:           qbr.year,
      workspaceName:  workspace?.name ?? 'QBR Deck',
      mspName:        branding.mspName,
      healthScore:    healthResult?.score  ?? qbr.healthScore,
      healthStatus:   healthResult?.status ?? qbr.healthStatus,
      branding:       { ...branding, footerText },
      generatedAt:    qbr.createdAt,
    })

    const resolvedSlides = qbr.slides
      ? resolveSlides(qbr.slides as Array<Record<string, unknown>>, placeholderCtx)
      : null

    // ── Defensive guard: sanitize the display copy before it ever leaves the
    // server. Raw qbr.slides above (and the stored DB value) is untouched —
    // see lib/placeholders.ts sanitizeResolvedSlides() for what this guards.
    let safeResolvedSlides = resolvedSlides
    if (resolvedSlides) {
      const sanitized = sanitizeResolvedSlides(resolvedSlides)
      safeResolvedSlides = sanitized.slides
      if (sanitized.hadUnresolvedTokens) {
        console.error('[unresolved-placeholder][saved-qbr-get]', qbr.id)
      }
    }

    return NextResponse.json({ ...qbr, resolvedSlides: safeResolvedSlides })
  } catch (err: any) {
    console.error('[saved-qbr-get]', params.qbrId, err)
    return NextResponse.json({ error: 'Failed to load QBR' }, { status: 500 })
  }
}

export async function PATCH(req: NextRequest, { params }: { params: { qbrId: string } }) {
  try {
    const { userId: clerkId } = auth()
    if (!clerkId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const membership = await getWorkspaceMembership(clerkId)
    if (!membership) return NextResponse.json({ error: 'Workspace not found' }, { status: 404 })

    if (!can.generateQBR(membership.role))
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })

    const qbr = await prisma.qBR.findFirst({
      where: { id: params.qbrId, workspaceId: membership.workspaceId, deletedAt: null },
      include: { client: true },
    })

    if (!qbr) return NextResponse.json({ error: 'Not found' }, { status: 404 })

    let body: unknown
    try {
      body = await req.json()
    } catch {
      return NextResponse.json({ error: 'Invalid request body' }, { status: 400 })
    }

    const parsed = patchSchema.safeParse(body)
    if (!parsed.success) {
      return NextResponse.json({ error: 'Invalid request body' }, { status: 400 })
    }
    const { slides } = parsed.data

    const updated = await prisma.qBR.update({
      where: { id: params.qbrId },
      data:  { slides: slides as any },
    })

    return NextResponse.json(updated)
  } catch (err: any) {
    console.error('[saved-qbr-patch]', params.qbrId, err)
    return NextResponse.json({ error: 'Failed to save QBR' }, { status: 500 })
  }
}